 
log_rotate_content: | 
  /var/log/redis/redis-server.log {
    weekly
    missingok
    rotate 12
    compress
    notifempty
  }

ami_id: 
go_version: 1.20
requirepassmain: ilegraredismainp4$$
requirepassreplica: ilegraredisreplicap4$$

aws_access_key: 
aws_secret_key: