pipeline {
    environment { 
        AWS_ACCESS_KEY = credentials('aws_access_key')
        AWS_SECRET_KEY = credentials('aws_secret_key')
        AWS_SESSION_TOKEN = credentials('aws_session_token')
    }

    agent any

    stages {
        stage('Config Environment Credential') {
            steps {
                sh 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY'
                sh 'export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_KEY"'
                sh 'export AWS_SESSION_TOKEN="$AWS_SESSION_TOKEN"'
            }
        }
        stage('Terraform Apply') {
            steps {
                sh 'terraform -chdir=redis/launch init'
                sh 'terraform -chdir=redis/launch apply  -auto-approve'
                sh 'terraform -chdir=redis/launch output > output.txt'
            }
        }
    }
}
