---

- name: Creating file zookeper service
  copy:
    dest: "/lib/systemd/system/calculator.service"
    content: |
      [Unit]
      Description=Calculator go application
      
      [Service]
      User=ec2-user
      WorkingDirectory=/home/ec2-user/app
      ExecStart=/bin/bash -c 'cd /home/ec2-user/app && go run .'
      
      [Install]
      WantedBy=multi-user.target
      
- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true

