---

- name: Ensure logrotate is installed
  package:
    name: logrotate
    state: present

- name: Verify if redis logrotate file exists
  stat:
    path: /etc/logrotate.d/redis
  register: logrotate_file


- name: Create Redis logrotate configuration
  copy:
    content: |
      /var/log/redis/redis-server.log {
        daily
        rotate 7
        compress
        delaycompress
        missingok
        notifempty
      }
    dest: /etc/logrotate.d/redis
