---

- name: Install redis
  package:
    name: redis
    state: latest
    update_cache: yes
  become: yes

- name: Install ufw
  package: 
    name: ufw
    state: latest
    
- name: Start Redis service
  service:
    name: redis
    state: started
    enabled: yes
    masked: no
  become: yes
