---

- name: Remove docker if installed from CentOS repo
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
    
- name: Install docker
  package:
    name: docker
    state: latest
    update_cache: yes
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
