---

- name: Set proxy for elasticseach and kibana port
  lineinfile:
    path: /etc/nginx/nginx.conf
    regex: '}(?!.*})'
    line : |
        server {
          listen 30092;
          server_name elasticsearch.local;

          location / {
            proxy_set_header Host            elasticsearch.local;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://elasticsearch.local;
          }
        }

        server {
          listen 30056;
          server_name kibana.com;

          location / {
            proxy_set_header Host            kibana.com;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://192.168.49.2:30056;
          }
        }

        }

- name: Set host for elasticseach and kibana
  lineinfile:
    path: /etc/hosts
    line: 192.168.49.2 elasticsearch.local kibana.com
