---

- name: Go version var is defined
  shell: echo "Go version {{ go_version }} is undefined"
  when: go_version is defined

- name: Go version var is undefined
  shell: echo "Go version is undefined"
  when: go_version is undefined

- name: Verify if Golang is installed
  shell: go version
  register: golang_exists
  failed_when: false

- name: Verify if Go 
  shell: go version
  register: golang_exists
  failed_when: false

- name: Verify if redis logrotate file exists
  stat:
    path: /etc/profile.d/go.sh
  register: go_sh_file

- name: Download go package
  get_url:
    url: https://go.dev/dl/go{{go_version}}.linux-amd64.tar.gz
    dest: /usr/local/{{ go_version }}.linux-amd64.tar.gz
  when: ( go_version is defined ) and ( "'not found' in redis_exists.stderr" )

- name: "Unzip go package"
  unarchive:
    src: "/usr/local/{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local/
    remote_src: yes
  when: ( go_version is defined ) and ( "'not found' in redis_exists.stderr" )

- name: Create go profile.d file for go path var
  copy:
    dest: /etc/profile.d/go.sh
    content: pathmunge /usr/local/go/bin
    mode: +x
  when: not go_sh_file.stat.exists

- name: Reload profile
  shell: . /etc/profile
  when: go_sh_file.stat.exists == false
