---

- name: Verify if redis logrotate file exists
  stat:
    path: /etc/logrotate.d/redis
  register: logrotate_file

- name: Uncomment logfile in redis.conf file
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^(^# logfile)'
    line: logfile /var/log/redis/redis.log

- name: Uncomment syslog enabled (to yes) in redis.conf file
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^(^# syslog-enabled no)'
    line: syslog-enabled yes

- name: Uncomment syslog ident (to redis) in redis.conf file
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^(^# syslog-ident)'
    line: syslog-ident redis

- name: Create logrotate file
  copy:
    dest: /etc/logrotate.d/redis
    content: "{{ log_rotate_content }}"
  when: logrotate_file.stat.exists == false

- name: Replace Redis logrotate file content
  copy:
    dest: /etc/logrotate.d/redis
    content: "{{ log_rotate_content }}"
  when: ( replace_logrotate is defined ) and ( replace_logrotate ) and (logrotate_file.stat.exists)
