---

- name: Apply ELK playbook 
  hosts: localhost
  become: yes

  tasks:

    - name: Increase virtual memory
      shell: sudo sysctl -w vm.max_map_count=262144

    - name: Start minikube
      ansible.builtin.systemd:
        state: restart
        name: minikube

    - name: Enable ingress
      command: /usr/local/bin/minikube addons enable ingress

    - name: Create elasticsearch service
      command: /usr/local/bin/kubectl apply -f /home/ec2-user/minikube/elasticsearch.yaml

    - name: Create elasticsearch ingress
      command: /usr/local/bin/kubectl apply -f /home/ec2-user/minikube/elasticsearch-ingress.yaml

    - name: Set host for elasticseach
      lineinfile:
        path: /etc/hosts
        line: 192.168.49.2 elasticsearch.local

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded