---

- name: Comment bind in redis.conf
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^(^bind 127.0.0.1)'
    line: "#bind 127.0.0.1 -::1"

- name: Set password in redis.conf
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^(^# requirepass)'
    line: "{{requirepassmain}}"

- name: Appendonly yes in redis.conf
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^(^appendonly no)'
    line: appendonly yes