---

- name: Install metricbeat
  package:
    name: metricbeat
    state: latest
    update_cache: yes
  become: yes

- name: Start metricbeat
  service:
    name: metricbeat
    state: started
    enabled: yes
