---

- name: Install metricbeat
  package:
    name: metricbeat
    state: latest
    update_cache: yes
  become: yes

- name: Start metricbeat
  service:
    name: metricbeat
    state: started
    enabled: yes

- name: Update metricbeat file
  copy:
    dest: "/etc/metricbeat/metricbeat.yml"
    content: |
      metricbeat.modules:
      - module: system
        metricsets:
          - cpu
          - filesystem
          - memory
          - network
          - process
        enabled: true
        period: 10s
        processes: ['.*']

      output.elasticsearch:
      hosts: ["http://34.236.151.175:30092"]
      timeout: 10
      
      setup.kibana:
        host: "http://34.236.151.175:30056"


      
- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    enabled: yes
    name: calculator
