---

- name: Edit Redis Replica config file
  hosts: localhost
  become: yes

  tasks:
    - name: install python2-pip
      yum:
        name: python2-pip
        state: present
        
    - name: Upgrade pip
      pip: name=pip state=latest
      tags:
        - packages
        
    - name: Ensure botocore and boto3 modules are installed
      pip:
        name: [ "boto3", "botocore"]

    - name: Get informations of created EC2 instance
      ec2_instance_info:
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        region: "{{ aws_region }}"
        filters:
          "tag:node": node-redis
          "tag:nodeType": main
          instance-state-name: ["running"]
      register: ec2_node_info

    - name: Comment bind in redis.conf file
      ansible.builtin.lineinfile:
        path: /etc/redis.conf
        regexp: '^(^bind 127.0.0.1)'
        line: "# bind 127.0.0.1 -::1"

    - name: Set requirepass in redis.conf file
      ansible.builtin.lineinfile:
        path: /etc/redis.conf
        regexp: '^(^# requirepass)'
        line: requirepass {{requirepassreplica}}

    - name: Set replicaof in redis.conf file
      ansible.builtin.lineinfile:
        path: /etc/redis.conf
        regexp: '^(^# slaveof)'
        line: slaveof {{ec2_node_info.instances[0].network_interfaces[0].private_ip_address}} 6379

    - name: Set masterauth in redis.conf file
      ansible.builtin.lineinfile:
        path: /etc/redis.conf
        regexp: '^(^# masterauth)'
        line: masterauth {{ requirepassmain }}

    - name: Restart Redis service
      service:
        name: redis
        state: restarted
        enabled: true
        masked: no
      become: yes
