---

- name: Get kubectl
  get_url: 
    url: https://dl.k8s.io/release/v1.28.1/bin/linux/amd64/kubectl
    dest: /tmp/

- name: Install kubectl
  command: install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl
  become: yes